# Generated by Django 3.1.2 on 2021-06-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
